sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t amosang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amosang/docker-react npm run test